version: '3.7'

services:

  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "8888:8888"
    networks:
      - audioNetwork

  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "9000:9000"
    networks:
      - audioNetwork
    depends_on:
      - config-service

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:9000/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
      SPRING_PROFILES_ACTIVE: path
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: resources-service
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://resources:8081
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /resources/**
      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]: StripPrefix=0
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: songs-service
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://songs:8082
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path= /songs/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[0]: StripPrefix=0
    networks:
      - audioNetwork
    depends_on:
      - config-service
      - discovery-service
      - resources
      - processor
      - songs

  resources:
    build:
      context: ./resources
    container_name: resources
    restart: on-failure
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      STORAGE_HOME: /home/storage
      AWS_ENDPOINT_URL: s3.localhost.localstack.cloud:4566
      STORAGES_MS_BASE_URI: http://storages:8083
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USER: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/audio
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:9000/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
    volumes:
      - ./storage:/home/storage
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - audioNetwork
    depends_on:
      - config-service
      - discovery-service
      - rabbitmq
      - postgres
      - localstack

  processor:
    build:
      context: ./resource-processor
    container_name: resource-processor
    restart: on-failure
    env_file:
      - .env
    environment:
      RESOURCES_MS_BASE_URI: http://resources:8081
      SONGS_MS_BASE_URI: http://songs:8082
      STORAGES_MS_BASE_URI: http://storages:8083
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USER: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - audioNetwork
    depends_on:
      - config-service
      - discovery-service
      - rabbitmq
      - resources
      - songs

  songs:
    build:
      context: ./songs
    container_name: songs
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/songs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - audioNetwork
    depends_on:
      - config-service
      - discovery-service
      - mongodb

  storages:
    build:
      context: ./storage
    container_name: storages
    restart: on-failure
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/audio
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:9000/eureka
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - audioNetwork
    depends_on:
      - config-service
      - discovery-service
      - postgres

  localstack:
    container_name: s3.localhost.localstack.cloud
    image: localstack/localstack:3.0.2
    hostname: s3.localhost.localstack.cloud
    ports:
      - "4566-4599:4566-4599"
    env_file:
      - .env
    environment:
      - DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_REGION=${AWS_DEFAULT_REGION}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SERVICES=s3
      - DEBUG=${DEBUG:-0}
      - DATA_DIR=${DATA_DIR:-./data/localstack/data}./data/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=s3.localhost.localstack.cloud
      - HOSTNAME_EXTERNAL=s3.localhost.localstack.cloud
      - USE_SSL=0
      - DISABLE_CORS_CHECKS=1
    networks:
      - audioNetwork
    volumes:
      - ./app-init/aws/setup-s3.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ${LOCALSTACK_VOLUME_DIR:-./data/localstack/volume}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - audioNetwork

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=audio
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5442:5432'
    volumes:
      - ./app-init/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pd_data:/var/lib/postgresql/data
    networks:
      - audioNetwork

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=audio@admin.com
      - PGADMIN_DEFAULT_PASSWORD=audio
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    ports:
      - "5050:80"
    volumes:
      - ./data/postgres/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27027:27017"
    env_file:
      - .env
    environment:
      - MONGODB_INITSCRIPTS_DIR=/docker-entrypoint-initdb.d
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - ./app-init/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db
    networks:
      - audioNetwork

# Volumes
volumes:
  data:
    driver: local
  pd_data:
    driver: local
  mongo_data:
    driver: local

#Network
networks:
  audioNetwork: