server:
  port: 8080

logstash:
  host: localhost:4560
  enabled: false

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
  profiles:
    active:
      - path
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8090/realms/My-Realm
            # Individual properties can also be provided this way
            token-uri: http://localhost:8090/realms/My-Realm/protocol/openid-connect/token
            authorization-uri: http://localhost:8090/realms/My-Realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8090/realms/My-Realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            scope: openid
            client-id: spring-gateway-client
            client-secret: 3RhEF8pqKTANrQ6BhfxaYVmcjTXsDK0u
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus




           