server:
  port: 8080

logstash:
  host: localhost:4560
  enabled: false

spring:
  profiles:
    active:
      - path
  application:
    name: api-gateway

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus




           