spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: resources-service
          uri: http://localhost:8081
          predicates:
            - Path= /resources/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: songs-service
          uri: http://localhost:8082
          predicates:
            - Path= /songs/**