server:
  port: 8080


logstash:
  host: localhost:4560
  enabled: false

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - path
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8090/realms/My-Realm
            # Individual properties can also be provided this way
            token-uri: ${spring.security.oauth2.client.provider.my-keycloak-provider.issuer-uri}/protocol/openid-connect/token
            authorization-uri: ${spring.security.oauth2.client.provider.my-keycloak-provider.issuer-uri}/protocol/openid-connect/auth
            userinfo-uri: ${spring.security.oauth2.client.provider.my-keycloak-provider.issuer-uri}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            client-id: spring-gateway-client
            client-secret: 3RhEF8pqKTANrQ6BhfxaYVmcjTXsDK0u

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus




           