spring:
  cloud:
    gateway:
      routes:
        - id: resources-service
          uri: http://localhost:8081
          predicates:
            - Path= /resources/**
        - id: songs-service
          uri: http://localhost:8082
          predicates:
            - Path= /songs/**